const product = [
    {
        id: 0,
        image: 'images/coords/coord1.jpg',
        title: 'Dark Blue casual wear co-ord set',
        price: 9999,
    },
    {
        id: 1,
        image: 'images/coords/coord2.jpg',
        title: 'Green floral printed party wear co-ord set.',
        price: 26999,
    },
    {
        id: 2,
        image: 'images/coords/coord3.jpg',
        title: 'Printed white parallel pants with pastel blue top.',
        price: 29999,
    },
    {
        id: 3,
        image: 'images/coords/coord4.jpg',
        title: 'Brown summer co-ord set.',
        price: 8999,
    },
    {
        id: 4,
        image: 'images/coords/coord5.jpg',
        title: 'Sleeved green summer co-ord set.',
        price: 7999,
    },
    {
        id: 5,
        image: 'images/oneps/onep1.jpeg',
        title: 'Creame casual wear dress.',
        price: 9999,
    },
    {
        id: 6,
        image: 'images/oneps/onep2.jpeg',
        title: 'Creame casual dress.',
        price: 10999,
    },
    {
        id: 7,
        image: 'images/oneps/onep3.jpeg',
        title: 'Brown summer dress.',
        price: 11999,
    },
    {
        id: 8,
        image: 'images/oneps/onep4.jpeg',
        title: 'Formal green long dress with pockets.',
        price: 8999,
    },
    {
        id: 9,
        image: 'images/oneps/onep5.jpeg',
        title: 'Party wear ankel length gown.',
        price: 19999,
    },
    {
        id: 10,
        image: 'images/bottoms/bottom1.jpeg',
        title: 'Parallel trousers in set of 4.',
        price: 7999,
    },
    {
        id: 11,
        image: 'images/bottoms/bottom2.jpeg',
        title: 'Short summer pants in set of 3.',
        price: 5999,
    },
    {
        id: 12,
        image: 'images/bottoms/bottom3.jpeg',
        title: 'Rainbow printed skirt.',
        price: 6999,
    },
    {
        id: 13,
        image: 'images/bottoms/bottom4.jpeg',
        title: 'Printed beige pants with side pockets.',
        price: 10999,
    },
    {
        id: 14,
        image: 'images/bottoms/bottom5.jpeg',
        title: 'Ankel length summer pants.',
        price: 11999,
    },
    {
        id: 15,
        image: 'images/tops/top1.jpg',
        title: 'Ethinic green crop top.',
        price: 8999,
    },
    {
        id: 16,
        image: 'images/tops/top2.jpg',
        title: 'Printed beige pants with side pockets.',
        price: 7999,
    },
    {
        id: 17,
        image: 'images/tops/top3.jpg',
        title: 'Purple half sleeve shirt.',
        price: 6999,
    },
    {
        id: 18,
        image: 'images/tops/top4.jpg',
        title: 'Cotton tank tops set of 5.',
        price: 5999,
    },
    {
        id: 19,
        image: 'images/tops/top5.jpg',
        title: 'Cotton tank tops set of 5.',
        price: 5999,
    },
];
